#############################################################################
# Makefile for building: QtNetworkMon
# Generated by qmake (2.01a) (Qt 4.2.1) on: ven. 25. mai 21:49:56 2007
# Project:  QtNetworkMon.pro
# Template: app
# Command: qmake -win32 -o Makefile QtNetworkMon.pro
#############################################################################

first: debug
install: debug-install
uninstall: debug-uninstall
MAKEFILE      = Makefile
QMAKE         = qmake
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = 
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		debug \
		release

debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: QtNetworkMon.pro  ..\..\..\libs\Qt\4.2.1\mkspecs\default\qmake.conf C:/david/libs/Qt/4.2.1/mkspecs/qconfig.pri \
		..\..\..\libs\Qt\4.2.1\mkspecs\features\qt_functions.prf \
		..\..\..\libs\Qt\4.2.1\mkspecs\features\qt_config.prf \
		..\..\..\libs\Qt\4.2.1\mkspecs\features\exclusive_builds.prf \
		..\..\..\libs\Qt\4.2.1\mkspecs\features\default_pre.prf \
		..\..\..\libs\Qt\4.2.1\mkspecs\features\win32\default_pre.prf \
		..\..\..\libs\Qt\4.2.1\mkspecs\features\debug.prf \
		..\..\..\libs\Qt\4.2.1\mkspecs\features\debug_and_release.prf \
		..\..\..\libs\Qt\4.2.1\mkspecs\features\default_post.prf \
		..\..\..\libs\Qt\4.2.1\mkspecs\features\win32\console.prf \
		..\..\..\libs\Qt\4.2.1\mkspecs\features\win32\rtti.prf \
		..\..\..\libs\Qt\4.2.1\mkspecs\features\win32\exceptions.prf \
		..\..\..\libs\Qt\4.2.1\mkspecs\features\win32\stl.prf \
		..\..\..\libs\Qt\4.2.1\mkspecs\features\shared.prf \
		..\..\..\libs\Qt\4.2.1\mkspecs\features\warn_on.prf \
		..\..\..\libs\Qt\4.2.1\mkspecs\features\qt.prf \
		..\..\..\libs\Qt\4.2.1\mkspecs\features\win32\thread.prf \
		..\..\..\libs\Qt\4.2.1\mkspecs\features\moc.prf \
		..\..\..\libs\Qt\4.2.1\mkspecs\features\resources.prf \
		..\..\..\libs\Qt\4.2.1\mkspecs\features\uic.prf
	$(QMAKE) -win32 -o Makefile QtNetworkMon.pro
C:/david/libs/Qt/4.2.1/mkspecs/qconfig.pri:
..\..\..\libs\Qt\4.2.1\mkspecs\features\qt_functions.prf:
..\..\..\libs\Qt\4.2.1\mkspecs\features\qt_config.prf:
..\..\..\libs\Qt\4.2.1\mkspecs\features\exclusive_builds.prf:
..\..\..\libs\Qt\4.2.1\mkspecs\features\default_pre.prf:
..\..\..\libs\Qt\4.2.1\mkspecs\features\win32\default_pre.prf:
..\..\..\libs\Qt\4.2.1\mkspecs\features\debug.prf:
..\..\..\libs\Qt\4.2.1\mkspecs\features\debug_and_release.prf:
..\..\..\libs\Qt\4.2.1\mkspecs\features\default_post.prf:
..\..\..\libs\Qt\4.2.1\mkspecs\features\win32\console.prf:
..\..\..\libs\Qt\4.2.1\mkspecs\features\win32\rtti.prf:
..\..\..\libs\Qt\4.2.1\mkspecs\features\win32\exceptions.prf:
..\..\..\libs\Qt\4.2.1\mkspecs\features\win32\stl.prf:
..\..\..\libs\Qt\4.2.1\mkspecs\features\shared.prf:
..\..\..\libs\Qt\4.2.1\mkspecs\features\warn_on.prf:
..\..\..\libs\Qt\4.2.1\mkspecs\features\qt.prf:
..\..\..\libs\Qt\4.2.1\mkspecs\features\win32\thread.prf:
..\..\..\libs\Qt\4.2.1\mkspecs\features\moc.prf:
..\..\..\libs\Qt\4.2.1\mkspecs\features\resources.prf:
..\..\..\libs\Qt\4.2.1\mkspecs\features\uic.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -win32 -o Makefile QtNetworkMon.pro

qmake_all: FORCE

make_default: debug-make_default release-make_default FORCE
make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile

debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
